### ISSUE TITLE
cant run on Emulator

### ISSUE THREAD

**Issue by bali94** [beerstorm-net/the_apple_sign_in#4] opened 2021-06-09 13:38 UTC
its working on Real device but not on ios emulator, Somebody knows why

**Comment by 3dluis** [comment] 2021-06-13 11:44
Try an emulate with IOS 13.7.

**Comment by zeusbaba** [comment] 2021-06-14 07:48
> Try an emulate with IOS 13.7.

I second that. a good workaround: it works fine with `iOS 13.x simulators` 

nb! iOS Emulators `v14.x` fails with Apple Signin. [see discussion](https://developer.apple.com/forums/thread/651533)

**Comment by zeusbaba** [comment] 2021-06-14 07:56
the issue is caused by `iOS 14 emulators` 
see details [from Apple forum >>](https://developer.apple.com/forums/thread/651533?answerId=675235022#675235022)  

p.s. closing this issue, feel free to open new issue

**Closed by zeusbaba** 2021-06-14 07:56 UTC
